name: React CI/CD to EC2

on:
  push:
    branches: [ operation ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: . 
        push: true 
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest
        build-args: |
          REACT_APP_PROD_BASE_URL=${{ secrets.REACT_APP_PROD_BASE_URL }}
          REACT_APP_KIBANA_URL=${{ secrets.REACT_APP_KIBANA_URL }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.EC2_HOST }}             
        username: ${{ secrets.EC2_USERNAME }}     
        key: ${{ secrets.EC2_SSH_KEY }}         
        script: |
          # 7-1. 최신 이미지 pull
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest
          
          # 7-2. 기존 컨테이너 중지 (있으면)
          docker stop my-react-app-container || true
          
          # 7-3. 기존 컨테이너 삭제 (있으면)
          docker rm my-react-app-container || true
          
          # 7-4. 새 컨테이너 실행 (EC2의 80번 포트와 컨테이너의 80번 포트 연결)
          docker run -d -p 3000:80 --name my-react-app-container ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest